### ISSUE TITLE
TypeError after v1.0.0-beta.122

### ISSUE THREAD

**Issue by dora1998** [3846masa/stylelint-browser-compat#704]
After v1.0.0-beta.122, we encounter the error below on running stylelint.

```
TypeError: Cannot read properties of undefined (reading '__compat')
    at /home/runner/work/web/web/node_modules/.pnpm/stylelint-browser-compat@1.0.0-beta.127_browserslist@4.23.0_stylelint@16.6.1_typescript@5.4.5_/node_modules/stylelint-browser-compat/lib/rule.js:56:19
    at async Promise.all (index 0)
```

I think this change may affects.
https://github.com/3846masa/stylelint-browser-compat/commit/820c73f940a776f982ea63f81daa543ce0cbbe2e#diff-0ceba63778a81ad3c2b980db18fb8c18cb54fb02b1f892290608b7eaa5fbb177

## Environment

- Node.js 20.12.2
- pnpm 9.1.3
- stylelint 16.6.1

**Comment by 3846masa** [comment]
We have fixed the probable cause and released it as v1.0.0-beta.128.

This release also includes the ability to display meaningful errors in case of similar issues.

If this release does not resolve the issue that you are having, please report the new errors that you see.
