### ISSUE TITLE
Add `repository` field to `package.json`

### ISSUE THREAD

**Issue by ybiquitous** [3846masa/stylelint-browser-compat#738]
Hello @3846masa, 👋🏼 

Thank you for creating the excellent package!

In this issue, I recommend adding the [`repository`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository) field to `package.json`. If added, `npm view` or `npm repo` will be much more helpful. For example:

```sh-session
$ npm view 'stylelint-browser-compat' repository

$ npm view 'stylelint' repository
{ type: 'git', url: 'git+https://github.com/stylelint/stylelint.git' }

$ npm repo --browser=false 'stylelint-browser-compat'
npm error no repository
npm error A complete log of this run can be found in: /Users/masafumi.koba/.npm/_logs/2024-07-12T02_52_40_138Z-debug-0.log

$ npm repo --browser=false 'stylelint'
stylelint repo available at the following URL:
https://github.com/stylelint/stylelint
```

It would be great if you could consider it. Thank you. 😃

**Comment by 3846masa** [comment]
Thank you for your report.
The repository field will be included in package.json after v1.0.0-beta.133.

**Comment by ybiquitous** [comment]
Excellent! Thank you! 👍🏼
