### ISSUE TITLE
show ids in error texts

### ISSUE THREAD

**Issue by dartess** [3846masa/stylelint-browser-compat#859]
Now we get errors like

```
✖  CSS animation for "::after" pseudo-element is not supported in Safari 15.
```

It would be great to have an id in the error text that is used for checking and that can be added to `allow.features`:

```
✖  CSS animation for "::after" pseudo-element is not supported in Safari 15 (selectors.after.animation_and_transition_support).
```

This would make the plugin much easier to use for beginners. I had to run the debugger to figure out how everything works. The line `Feature names are from @mdn/browser-compat-data.` is not very helpful for me.

I could do a PR with this.

**Comment by 3846masa** [comment]
Thanks for reporting. This is released as v1.0.0-beta.145.
